default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tutors_development

test:
  <<: *default
  database: tutors_test

production:
  <<: *default
  database: tutors_production
  username: tutors
  password: <%= ENV['TUTORS_DATABASE_PASSWORD'] %>
