SUBJECTS = [
  'Algebra I',
  'Algebra II',
  'Biology I',
  'Biology II',
  'Calculus AB',
  'Calculus BC',
  'Chemistry I',
  'Chemistry II',
  'Computer Science I',
  'Computer Science II',
  'Economics',
  'English I',
  'English II',
  'English III',
  'English IV',
  'French I',
  'French II',
  'French III',
  'French IV',
  'Geometry',
  'Government',
  'HPMS Earth Science',
  'HPMS Pre Algebra',
  'IPC',
  'Latin I',
  'Latin II',
  'Latin III',
  'Physics I',
  'Pre-Calculus',
  'Spanish I',
  'Spanish II',
  'Spanish III',
  'Spanish IV',
  'Statistics',
  'Texas History-7th Grade',
  'U.S. History',
  'World Geography',
  'World History',
]
